# Generated by Django 5.0.3 on 2024-04-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
