# Generated by Django 5.0.3 on 2024-04-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('sequency', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
